server:
  port: 10001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tree?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 5
      pool-name: DatebookHikariCP
  jpa:
    show-sql: true